### ISSUE TITLE
resources keys

### ISSUE THREAD

**Issue by jcheron** [ovide/phest#1]
Hello,
First : thank you for your Rest library
Secondly : I try to use it...

When I try something like this in my bootstrap file, 

``` php
$app->addResources([
    'myresource/path'             => MyResource::class,
    'myresource/path/subresource' => SubResource::class
]);
```

I assumed that the array keys are used to define the routes, but they are never used.
So I use the static member **PATH** of each of my controllers:
Is this normal?

**Comment by ovide** [comment]
Sorry for that!
The thing is i'm waiting for phalcon 2.0 stable to continue with this project, but I can push some changes this night and update the README file

The current behavior is as you say:

``` php
$app->addResources([MyResource::class, OtherResource::class]);
```

And uses the PATH constant.
https://github.com/ovide/phest/blob/master/src/App.php#L118

**Comment by jcheron** [comment]
I understand that.
Meanwhile Phalcon 2.0, I slightly modified the **mountResource** method, so do not systematically assign a value to the **PATH** constant

``` php
    public function mountResource($controller)
    {
        $path=$controller::PATH;
        if($path==="")
            $path="/".strtolower($controller);
        $rx  = $controller::RX;
        $col = new Collection();
        $col->setHandler($controller, true);
        $col->setPrefix($path);
  ...
    }
```
